#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Yttrian\Advent2024\Support\RunCommand;

$application = new Application();

$application->add(new RunCommand());

$application->run();
